import type {
  Agency,
  Badge,
  CommunityPost,
  Destination,
  Experience,
  Traveler,
  Trip,
  User,
} from "./types";

// ─── Unsplash Photo IDs ───────────────────────────────────────────────────────
// Using stable Unsplash photo IDs for consistent, beautiful imagery
const U = (id: string, w = 1200, q = 85) =>
  `https://images.unsplash.com/${id}?w=${w}&q=${q}&auto=format&fit=crop`;

// ─── Destinations ─────────────────────────────────────────────────────────────

export const DESTINATIONS: Destination[] = [
  {
    id: "spiti",
    name: "Spiti Valley",
    country: "India",
    continent: "Asia",
    tagline: "The cold desert on the roof of the world",
    image: U("photo-1626621341517-bbf3d9990a23", 600),
    coverImage: U("photo-1626621341517-bbf3d9990a23", 1400),
    lat: 32.2432,
    lng: 78.0325,
    countryCode: "IN",
    trending: true,
  },
  {
    id: "japan",
    name: "Kyoto",
    country: "Japan",
    continent: "Asia",
    tagline: "Where ancient temples meet neon dreams",
    image: U("photo-1493976040374-85c8e12f0c0e", 600),
    coverImage: U("photo-1493976040374-85c8e12f0c0e", 1400),
    lat: 35.0116,
    lng: 135.7681,
    countryCode: "JP",
    trending: true,
  },
  {
    id: "bali",
    name: "Bali",
    country: "Indonesia",
    continent: "Asia",
    tagline: "Gods, rice fields and ocean sunsets",
    image: U("photo-1537996194471-e657df975ab4", 600),
    coverImage: U("photo-1537996194471-e657df975ab4", 1400),
    lat: -8.3405,
    lng: 115.092,
    countryCode: "ID",
    trending: false,
  },
  {
    id: "iceland",
    name: "Iceland",
    country: "Iceland",
    continent: "Europe",
    tagline: "Northern lights, glaciers, and pure silence",
    image: U("photo-1504893524553-b855bce32c67", 600),
    coverImage: U("photo-1504893524553-b855bce32c67", 1400),
    lat: 64.9631,
    lng: -19.0208,
    countryCode: "IS",
    trending: true,
  },
  {
    id: "morocco",
    name: "Marrakech",
    country: "Morocco",
    continent: "Africa",
    tagline: "Pink walls, spice markets and Sahara sunsets",
    image: U("photo-1539037116277-4db20889f2d4", 600),
    coverImage: U("photo-1539037116277-4db20889f2d4", 1400),
    lat: 31.6295,
    lng: -7.9811,
    countryCode: "MA",
    trending: false,
  },
  {
    id: "peru",
    name: "Machu Picchu",
    country: "Peru",
    continent: "South America",
    tagline: "Lost city of the Inca, found by the world",
    image: U("photo-1526392060635-9d6019884377", 600),
    coverImage: U("photo-1526392060635-9d6019884377", 1400),
    lat: -13.1631,
    lng: -72.545,
    countryCode: "PE",
    trending: false,
  },
  {
    id: "newzealand",
    name: "Queenstown",
    country: "New Zealand",
    continent: "Oceania",
    tagline: "The adventure capital of the universe",
    image: U("photo-1476514525535-07fb3b4ae5f1", 600),
    coverImage: U("photo-1476514525535-07fb3b4ae5f1", 1400),
    lat: -45.0312,
    lng: 168.6626,
    countryCode: "NZ",
    trending: true,
  },
  {
    id: "thailand",
    name: "Chiang Mai",
    country: "Thailand",
    continent: "Asia",
    tagline: "Temples, elephants and street food bliss",
    image: U("photo-1528360983277-13d401cdc186", 600),
    coverImage: U("photo-1528360983277-13d401cdc186", 1400),
    lat: 18.7061,
    lng: 98.9817,
    countryCode: "TH",
    trending: false,
  },
  {
    id: "santorini",
    name: "Santorini",
    country: "Greece",
    continent: "Europe",
    tagline: "Blue domes, white walls, Aegean magic",
    image: U("photo-1570077188670-e3a8d69ac5ff", 600),
    coverImage: U("photo-1570077188670-e3a8d69ac5ff", 1400),
    lat: 36.3932,
    lng: 25.4615,
    countryCode: "GR",
    trending: true,
  },
  {
    id: "patagonia",
    name: "Patagonia",
    country: "Argentina",
    continent: "South America",
    tagline: "Wild winds, granite towers, zero signal",
    image: U("photo-1519681393784-d120267933ba", 600),
    coverImage: U("photo-1519681393784-d120267933ba", 1400),
    lat: -51.6230,
    lng: -72.6789,
    countryCode: "AR",
    trending: true,
  },
  {
    id: "swiss-alps",
    name: "Swiss Alps",
    country: "Switzerland",
    continent: "Europe",
    tagline: "Paraglide over glaciers, ski the Matterhorn",
    image: U("photo-1527668752968-14dc70a27c95", 600),
    coverImage: U("photo-1527668752968-14dc70a27c95", 1400),
    lat: 46.0207,
    lng: 7.7491,
    countryCode: "CH",
    trending: false,
  },
  {
    id: "cappadocia",
    name: "Cappadocia",
    country: "Turkey",
    continent: "Europe",
    tagline: "Hot air balloons over fairy chimneys at dawn",
    image: U("photo-1509316785289-025f5b846b35", 600),
    coverImage: U("photo-1509316785289-025f5b846b35", 1400),
    lat: 38.6431,
    lng: 34.8283,
    countryCode: "TR",
    trending: true,
  },
  {
    id: "maldives",
    name: "Maldives",
    country: "Maldives",
    continent: "Asia",
    tagline: "Overwater bungalows, reefs, and nothing else",
    image: U("photo-1514282401047-d79a71a590e8", 600),
    coverImage: U("photo-1514282401047-d79a71a590e8", 1400),
    lat: 3.2028,
    lng: 73.2207,
    countryCode: "MV",
    trending: true,
  },
  {
    id: "norway",
    name: "Norwegian Fjords",
    country: "Norway",
    continent: "Europe",
    tagline: "Cruise fjords, hike cliffs, see the midnight sun",
    image: U("photo-1531722569936-825d4eaf1af1", 600),
    coverImage: U("photo-1531722569936-825d4eaf1af1", 1400),
    lat: 60.4720,
    lng: 8.4689,
    countryCode: "NO",
    trending: false,
  },
  {
    id: "vietnam",
    name: "Ha Long Bay",
    country: "Vietnam",
    continent: "Asia",
    tagline: "Limestone karsts, jade water, floating villages",
    image: U("photo-1528181304800-259b08848526", 600),
    coverImage: U("photo-1528181304800-259b08848526", 1400),
    lat: 20.9101,
    lng: 107.1839,
    countryCode: "VN",
    trending: true,
  },
  {
    id: "canada",
    name: "Banff",
    country: "Canada",
    continent: "North America",
    tagline: "Turquoise lakes, elk, and the Canadian Rockies",
    image: U("photo-1567721913486-6585f069b3d2", 600),
    coverImage: U("photo-1567721913486-6585f069b3d2", 1400),
    lat: 51.1784,
    lng: -115.5708,
    countryCode: "CA",
    trending: false,
  },
];

// ─── Agencies ─────────────────────────────────────────────────────────────────

export const AGENCIES: Agency[] = [
  {
    id: "agency-wanderlust",
    name: "Wanderlust Collective",
    logo: U("photo-1527838832700-5059252407fa", 200),
    coverImage: U("photo-1464822759023-fed622ff2c3b", 1200),
    verified: true,
    rating: 4.9,
    reviewCount: 847,
    tripsCompleted: 312,
    yearsActive: 7,
    bio: "We don't run tours. We curate stories. 7 years of crafting unforgettable adventures for the bold generation.",
    specialties: ["Backpacking", "Trekking", "Camping"],
    location: "Delhi, India",
    instagram: "@wanderlust.collective",
  },
  {
    id: "agency-nomad",
    name: "Nomad Routes",
    logo: U("photo-1534438327276-14e5300c3a48", 200),
    coverImage: U("photo-1476514525535-07fb3b4ae5f1", 1200),
    verified: true,
    rating: 4.8,
    reviewCount: 523,
    tripsCompleted: 198,
    yearsActive: 4,
    bio: "Born from a group of friends who quit their jobs to travel the world. Now we take you along.",
    specialties: ["Solo", "Road Trips", "Digital Nomad"],
    location: "Bangalore, India",
    instagram: "@nomad.routes",
  },
  {
    id: "agency-surf",
    name: "Salt & Waves",
    logo: U("photo-1502680390469-be75c86b636f", 200),
    coverImage: U("photo-1507525428034-b723cf961d3e", 1200),
    verified: true,
    rating: 4.7,
    reviewCount: 389,
    tripsCompleted: 145,
    yearsActive: 5,
    bio: "Ocean-obsessed humans running surf camps, beach retreats and island hopping adventures.",
    specialties: ["Surfing", "Wellness", "Camping"],
    location: "Goa, India",
    instagram: "@saltandwaves",
  },
];

// ─── Travelers (sample avatars) ───────────────────────────────────────────────

export const TRAVELERS: Traveler[] = [
  {
    id: "t1",
    name: "Aryan M",
    avatar: U("photo-1507003211169-0a1dd7228f2d", 100),
    hometown: "Mumbai",
    tripsCount: 14,
  },
  {
    id: "t2",
    name: "Priya K",
    avatar: U("photo-1494790108377-be9c29b29330", 100),
    hometown: "Bangalore",
    tripsCount: 8,
  },
  {
    id: "t3",
    name: "Rohan S",
    avatar: U("photo-1500648767791-00dcc994a43e", 100),
    hometown: "Delhi",
    tripsCount: 22,
  },
  {
    id: "t4",
    name: "Aisha N",
    avatar: U("photo-1438761681033-6461ffad8d80", 100),
    hometown: "Hyderabad",
    tripsCount: 6,
  },
  {
    id: "t5",
    name: "Karan T",
    avatar: U("photo-1472099645785-5658abf4ff4e", 100),
    hometown: "Pune",
    tripsCount: 19,
  },
  {
    id: "t6",
    name: "Meera R",
    avatar: U("photo-1534528741775-53994a69daeb", 100),
    hometown: "Chennai",
    tripsCount: 11,
  },
];

// ─── Experiences ──────────────────────────────────────────────────────────────

export const EXPERIENCES: Experience[] = [
  {
    id: "exp-spiti",
    title: "Spiti Valley Motorbike Expedition",
    tagline: "Ride through the roof of the world",
    description:
      "Strap on your helmet and ride through one of Earth's most dramatic landscapes. Spiti Valley sits at 12,500 feet — cold desert, bone-white monasteries, and roads that test your resolve. This isn't a vacation. It's a reset button for your soul. You'll cross the legendary Kunzum Pass, camp beside Chandratal Lake, and arrive at Key Monastery with the kind of exhaustion that feels like glory. 10 days, 12 riders, one unforgettable story.",
    agency: AGENCIES[0],
    destination: DESTINATIONS[0],
    heroImage: U("photo-1626621341517-bbf3d9990a23", 1400),
    gallery: [
      U("photo-1626621341517-bbf3d9990a23", 900),
      U("photo-1464822759023-fed622ff2c3b", 900),
      U("photo-1551632811-561732d1e306", 900),
      U("photo-1476514525535-07fb3b4ae5f1", 900),
    ],
    price: 45000,
    currency: "INR",
    duration: "10 Days",
    durationDays: 10,
    dates: [
      {
        id: "d1",
        startDate: "2026-09-05",
        endDate: "2026-09-14",
        seatsTotal: 12,
        seatsLeft: 3,
      },
      {
        id: "d2",
        startDate: "2026-10-01",
        endDate: "2026-10-10",
        seatsTotal: 12,
        seatsLeft: 8,
      },
    ],
    seatsTotal: 12,
    seatsLeft: 3,
    travelers: TRAVELERS.slice(0, 4),
    rating: 4.9,
    reviewCount: 127,
    category: "Backpacking",
    tags: ["Motorbike", "Mountains", "Himalayas", "High Altitude"],
    difficulty: "Challenging",
    included: [
      "Royal Enfield Himalayan (shared)",
      "9 nights accommodation",
      "All meals on route",
      "Fuel for the ride",
      "Permit fees & inner line passes",
      "Experienced ride leader",
      "Support vehicle",
      "Mechanic on standby",
      "First aid kit",
    ],
    excluded: [
      "Flights to/from Manali",
      "Personal riding gear (helmets available for rent)",
      "Travel insurance",
      "Personal expenses",
      "Anything not listed above",
    ],
    itinerary: [
      {
        day: 1,
        title: "Arrive in Manali — Meet Your Crew",
        description:
          "Land in Manali and check into the basecamp hostel. Evening gear check, briefing session, and team dinner. Get to know your fellow riders over momos and chai.",
        activities: ["Gear check", "Route briefing", "Team dinner"],
        meals: ["Dinner"],
        accommodation: "The Manali Basecamp Hostel",
      },
      {
        day: 2,
        title: "Manali to Kaza via Rohtang Pass",
        description:
          "The ride begins. Cross the mighty Rohtang Pass and descend into the cold desert. Watch the landscape transform dramatically as you enter Spiti.",
        activities: ["Ride through Rohtang", "Spiti entry checkpoint", "Kaza exploration"],
        meals: ["Breakfast", "Packed Lunch", "Dinner"],
        accommodation: "Kaza Homestay",
        image: U("photo-1464822759023-fed622ff2c3b", 600),
      },
      {
        day: 3,
        title: "Key Monastery & Kibber Village",
        description:
          "Morning meditation at the 1000-year-old Key Monastery. Ride up to Kibber — one of the world's highest villages with a motor road. Afternoon free to wander.",
        activities: ["Key Monastery visit", "Kibber ride", "Photography"],
        meals: ["Breakfast", "Lunch", "Dinner"],
        accommodation: "Kaza Homestay",
      },
      {
        day: 4,
        title: "Chandratal Lake — The Moon Lake",
        description:
          "Camp beside the turquoise Chandratal Lake at 14,100 feet. Night sky gazing like you've never seen before. This is the highlight most riders say they'll never forget.",
        activities: ["Ride to Chandratal", "Camp setup", "Star gazing"],
        meals: ["Breakfast", "Lunch", "Campfire Dinner"],
        accommodation: "Chandratal Camp",
        image: U("photo-1476514525535-07fb3b4ae5f1", 600),
      },
    ],
    highlights: [
      "Chandratal Lake at 14,100 feet",
      "1000-year-old Key Monastery",
      "Kunzum Pass (4,590m)",
      "Kibber Village — one of the world's highest",
      "Camping under Milky Way",
    ],
    faqs: [
      {
        question: "Do I need riding experience?",
        answer:
          "You should be comfortable riding a 350-500cc motorcycle. We don't require an off-road license but some hill-riding experience is strongly recommended.",
      },
      {
        question: "What's the weather like?",
        answer:
          "September is ideal — clear skies, manageable roads. October gets colder and some passes may close. Pack layers regardless.",
      },
      {
        question: "Is this safe?",
        answer:
          "We've completed 40+ Spiti rides. Full support vehicle, experienced leader, mechanic, and first aid are always with the group. We don't ride after dark.",
      },
    ],
    reviews: [
      {
        id: "r1",
        author: TRAVELERS[0],
        rating: 5,
        text: "This changed my life. Not kidding. The Chandratal night under the Milky Way is something I will describe to my grandkids someday.",
        date: "2025-10-18",
        tripDate: "Oct 2025",
        verified: true,
        images: [U("photo-1476514525535-07fb3b4ae5f1", 400)],
      },
      {
        id: "r2",
        author: TRAVELERS[2],
        rating: 5,
        text: "The team at Wanderlust Collective are absolute legends. Every detail was taken care of. The food was surprisingly incredible for the altitude.",
        date: "2025-09-28",
        tripDate: "Sep 2025",
        verified: true,
      },
    ],
    lat: 32.2432,
    lng: 78.0325,
    address: "Manali to Kaza, Spiti Valley, HP",
    trending: true,
    aiPick: true,
    isWeekendEscape: false,
    isFeatured: true,
    badge: "Hot",
  },

  {
    id: "exp-japan-anime",
    title: "Anime & Culture Deep Dive — Tokyo & Kyoto",
    tagline: "Live your favorite anime IRL",
    description:
      "This isn't a regular Japan trip. It's a pilgrimage for anime fans, manga lovers, and people who grew up dreaming of Akihabara. We hit every cultural hotspot — cosplay districts, themed cafes, Studio Ghibli Museum, ancient Kyoto temples — and blend it into 8 days that feel like falling into your favorite show.",
    agency: AGENCIES[1],
    destination: DESTINATIONS[1],
    heroImage: U("photo-1493976040374-85c8e12f0c0e", 1400),
    gallery: [
      U("photo-1493976040374-85c8e12f0c0e", 900),
      U("photo-1528360983277-13d401cdc186", 900),
      U("photo-1540959733332-eab4deabeeaf", 900),
    ],
    price: 120000,
    currency: "INR",
    duration: "8 Days",
    durationDays: 8,
    dates: [
      {
        id: "d1",
        startDate: "2026-11-10",
        endDate: "2026-11-17",
        seatsTotal: 15,
        seatsLeft: 6,
      },
    ],
    seatsTotal: 15,
    seatsLeft: 6,
    travelers: TRAVELERS.slice(1, 5),
    rating: 4.8,
    reviewCount: 93,
    category: "Anime & Pop Culture",
    tags: ["Anime", "Japan", "Culture", "Cosplay", "Tokyo", "Kyoto"],
    difficulty: "Easy",
    included: [
      "Return flights Delhi-Tokyo",
      "7 nights accommodation (capsule hotel + ryokan combo)",
      "JR Pass (7 days)",
      "Studio Ghibli Museum tickets",
      "Cosplay workshop",
      "3 themed dining experiences",
      "Experienced Japan guide",
    ],
    excluded: [
      "Visa fees (~₹6,000)",
      "Personal shopping",
      "Additional meals",
      "Travel insurance",
    ],
    itinerary: [
      {
        day: 1,
        title: "Land in Tokyo — Shibuya Crossing at Night",
        description:
          "Arrive at Narita, check into the capsule hotel, and make your way to the iconic Shibuya crossing at night. Your Japan chapter begins.",
        activities: ["Airport transfer", "Shibuya crossing", "Team ramen dinner"],
        meals: ["Dinner"],
        accommodation: "Nine Hours Capsule Hotel, Shinjuku",
        image: U("photo-1540959733332-eab4deabeeaf", 600),
      },
      {
        day: 2,
        title: "Akihabara & Cosplay Day",
        description:
          "Full day in Electric Town. Morning cosplay workshop, afternoon browsing manga stores and arcades, evening maid cafe experience.",
        activities: ["Cosplay workshop", "Akihabara exploration", "Maid cafe", "Gaming arcade"],
        meals: ["Breakfast", "Lunch at Akihabara"],
        accommodation: "Nine Hours Capsule Hotel, Shinjuku",
      },
    ],
    highlights: [
      "Studio Ghibli Museum (Mitaka)",
      "Akihabara Electric Town",
      "Cosplay workshop in Harajuku",
      "Fushimi Inari Shrine at dawn",
      "Traditional ryokan overnight stay",
    ],
    faqs: [
      {
        question: "Do I need to know Japanese?",
        answer:
          "Not at all. Our guide handles all logistics. Most tourist areas have English signs. Bonus: Google Translate camera mode is your superpower.",
      },
    ],
    reviews: [
      {
        id: "r1",
        author: TRAVELERS[3],
        rating: 5,
        text: "I've watched anime my whole life and actually standing in Shibuya at night made me cry. Worth every rupee and more.",
        date: "2025-12-01",
        tripDate: "Nov 2025",
        verified: true,
      },
    ],
    lat: 35.0116,
    lng: 135.7681,
    address: "Tokyo & Kyoto, Japan",
    trending: true,
    aiPick: true,
    isWeekendEscape: false,
    isFeatured: true,
    badge: "Sold Fast",
  },

  {
    id: "exp-bali-surf",
    title: "Bali Surf & Soul Retreat",
    tagline: "Learn to surf. Learn to breathe.",
    description:
      "7 days on Bali's legendary Canggu and Seminyak coast. Every morning you're in the ocean learning to read waves. Every evening you're watching the sun melt into the Indian Ocean. In between: yoga at sunset, smoothie bowls, rice paddies on motorbikes, and a nightlife that's both wild and deeply restful somehow.",
    agency: AGENCIES[2],
    destination: DESTINATIONS[2],
    heroImage: U("photo-1537996194471-e657df975ab4", 1400),
    gallery: [
      U("photo-1537996194471-e657df975ab4", 900),
      U("photo-1502680390469-be75c86b636f", 900),
      U("photo-1507525428034-b723cf961d3e", 900),
    ],
    price: 55000,
    currency: "INR",
    duration: "7 Days",
    durationDays: 7,
    dates: [
      {
        id: "d1",
        startDate: "2026-08-20",
        endDate: "2026-08-26",
        seatsTotal: 10,
        seatsLeft: 2,
      },
      {
        id: "d2",
        startDate: "2026-09-15",
        endDate: "2026-09-21",
        seatsTotal: 10,
        seatsLeft: 7,
      },
    ],
    seatsTotal: 10,
    seatsLeft: 2,
    travelers: TRAVELERS.slice(0, 5),
    rating: 4.9,
    reviewCount: 201,
    category: "Surfing",
    tags: ["Surf", "Yoga", "Bali", "Beach", "Wellness"],
    difficulty: "Easy",
    included: [
      "6 nights at surf villa in Canggu",
      "Daily surf lessons (1.5 hr)",
      "Surfboard rental",
      "Daily breakfast",
      "Sunset yoga (4 sessions)",
      "Temple visit & cultural tour",
      "Airport transfers",
    ],
    excluded: [
      "Flights to Bali",
      "Lunch and dinner",
      "Visa on arrival (~$35)",
      "Personal expenses",
    ],
    itinerary: [
      {
        day: 1,
        title: "Arrive in Canggu — Welcome Dinner",
        description:
          "Settle into the surf villa, explore the neighborhood on foot or bicycle. Welcome dinner on the beach.",
        activities: ["Check-in", "Canggu walk", "Sunset welcome dinner"],
        meals: ["Dinner"],
        accommodation: "Canggu Surf Villa",
        image: U("photo-1537996194471-e657df975ab4", 600),
      },
      {
        day: 2,
        title: "First Wave — Beginner Surf Session",
        description:
          "6am start. Learn stance, paddling and popping up on the board on a mellow beach break. Morning yoga follows. Afternoon free.",
        activities: ["Surf lesson", "Morning yoga", "Rest & explore"],
        meals: ["Breakfast"],
        accommodation: "Canggu Surf Villa",
      },
    ],
    highlights: [
      "Catch your first wave",
      "Sunset yoga on the beach",
      "Tanah Lot temple at dusk",
      "Tegalalang rice terrace trek",
      "Canggu nightlife and coffee shops",
    ],
    faqs: [
      {
        question: "Can complete beginners join?",
        answer:
          "Absolutely. Most of our guests have never surfed. Our instructors are certified and ultra patient.",
      },
    ],
    reviews: [
      {
        id: "r1",
        author: TRAVELERS[1],
        rating: 5,
        text: "Stood up on the board on day 2. Actually screamed with joy in the ocean. One of my top 3 life moments.",
        date: "2025-08-28",
        tripDate: "Aug 2025",
        verified: true,
      },
    ],
    lat: -8.3405,
    lng: 115.092,
    address: "Canggu, Bali, Indonesia",
    trending: false,
    aiPick: true,
    isWeekendEscape: false,
    isFeatured: false,
    badge: "2 left",
  },

  {
    id: "exp-iceland-aurora",
    title: "Iceland Aurora & Glacier Chase",
    tagline: "Chase lights. Walk on ice. Feel small.",
    description:
      "Eight days in Iceland during peak Northern Lights season. We'll chase the aurora across volcanic landscapes, hike on ancient glaciers, soak in hidden hot springs, and watch waterfalls thunder into mist. Every day looks like a screensaver and that's not an exaggeration.",
    agency: AGENCIES[0],
    destination: DESTINATIONS[3],
    heroImage: U("photo-1504893524553-b855bce32c67", 1400),
    gallery: [
      U("photo-1504893524553-b855bce32c67", 900),
      U("photo-1476514525535-07fb3b4ae5f1", 900),
    ],
    price: 175000,
    currency: "INR",
    duration: "8 Days",
    durationDays: 8,
    dates: [
      {
        id: "d1",
        startDate: "2026-12-10",
        endDate: "2026-12-17",
        seatsTotal: 8,
        seatsLeft: 4,
      },
    ],
    seatsTotal: 8,
    seatsLeft: 4,
    travelers: TRAVELERS.slice(2, 6),
    rating: 5.0,
    reviewCount: 58,
    category: "Trekking",
    tags: ["Aurora", "Iceland", "Glacier", "Northern Lights", "Arctic"],
    difficulty: "Moderate",
    included: [
      "Return flights from Delhi",
      "7 nights accommodation (guesthouses + glacier hut)",
      "Glacier hiking with crampons & guide",
      "Northern Lights jeep chase (3 nights)",
      "Golden Circle tour",
      "Blue Lagoon entry",
      "All breakfasts + 4 dinners",
      "Thermal gear rental",
    ],
    excluded: ["Visa fees", "Lunches", "Personal expenses", "Travel insurance"],
    itinerary: [
      {
        day: 1,
        title: "Reykjavik — The World's Coolest Capital",
        description:
          "Arrive in Reykjavik. Explore the colorful city, visit Hallgrímskirkja church, grab traditional lamb soup. First aurora alert at 11pm.",
        activities: ["City walk", "Hallgrímskirkja", "First aurora watch"],
        meals: ["Dinner"],
        accommodation: "Reykjavik Guesthouse",
        image: U("photo-1504893524553-b855bce32c67", 600),
      },
    ],
    highlights: [
      "Northern Lights on 3 dedicated chase nights",
      "Glacier hike on Vatnajökull",
      "Seljalandsfoss waterfall (walk behind it)",
      "Blue Lagoon thermal spa",
      "Black sand beaches of Reynisfjara",
    ],
    faqs: [
      {
        question: "Is aurora sighting guaranteed?",
        answer:
          "No one can guarantee natural phenomena, but December has 16+ hours of darkness and we have 3 dedicated aurora chases with expert guides and real-time KP index monitoring.",
      },
    ],
    reviews: [
      {
        id: "r1",
        author: TRAVELERS[4],
        rating: 5,
        text: "The Northern Lights danced above our heads for 45 minutes. I stood there crying like a child. Zero regrets. Already booked again for next year.",
        date: "2025-12-20",
        tripDate: "Dec 2025",
        verified: true,
        images: [U("photo-1504893524553-b855bce32c67", 400)],
      },
    ],
    lat: 64.9631,
    lng: -19.0208,
    address: "Reykjavik, Iceland (Ring Road)",
    trending: true,
    aiPick: false,
    isWeekendEscape: false,
    isFeatured: true,
    badge: "Top Rated",
  },

  {
    id: "exp-coorg-weekend",
    title: "Coorg Coffee & Trek Weekend",
    tagline: "Escape Bangalore in 4 hours",
    description:
      "The perfect weekend escape from the city. Head to Coorg's misty coffee estates, trek through spice plantations, take a dip in Iruppu Falls, and sleep under the stars at a boutique estate. You leave Monday rested, centered, and smelling faintly of cardamom.",
    agency: AGENCIES[1],
    destination: {
      id: "coorg",
      name: "Coorg",
      country: "India",
      continent: "Asia",
      tagline: "Scotland of India",
      image: U("photo-1464822759023-fed622ff2c3b", 600),
      coverImage: U("photo-1464822759023-fed622ff2c3b", 1400),
      lat: 12.4244,
      lng: 75.7382,
      countryCode: "IN",
      trending: true,
    },
    heroImage: U("photo-1464822759023-fed622ff2c3b", 1400),
    gallery: [U("photo-1464822759023-fed622ff2c3b", 900), U("photo-1476514525535-07fb3b4ae5f1", 900)],
    price: 8500,
    currency: "INR",
    duration: "3 Days",
    durationDays: 3,
    dates: [
      {
        id: "d1",
        startDate: "2026-08-22",
        endDate: "2026-08-24",
        seatsTotal: 20,
        seatsLeft: 11,
      },
      {
        id: "d2",
        startDate: "2026-08-29",
        endDate: "2026-08-31",
        seatsTotal: 20,
        seatsLeft: 5,
      },
    ],
    seatsTotal: 20,
    seatsLeft: 11,
    travelers: TRAVELERS.slice(0, 3),
    rating: 4.7,
    reviewCount: 312,
    category: "Backpacking",
    tags: ["Weekend", "Coffee", "Trek", "Nature", "Waterfall"],
    difficulty: "Easy",
    included: [
      "2 nights at coffee estate",
      "All meals",
      "Coffee estate guided tour",
      "Iruppu Falls trek",
      "Spice plantation walk",
      "Transportation from Bangalore",
    ],
    excluded: ["Personal expenses", "Alcohol", "Anything not listed"],
    itinerary: [
      {
        day: 1,
        title: "Bus from Bangalore — Coffee Estate Arrival",
        description: "Depart Bangalore early morning. Arrive at estate by noon. Afternoon coffee tour and evening bonfire.",
        activities: ["Estate arrival", "Coffee plantation tour", "Bonfire evening"],
        meals: ["Lunch", "Dinner"],
        accommodation: "Coorg Estate Bungalow",
      },
    ],
    highlights: [
      "Private coffee estate stay",
      "Iruppu Falls trek",
      "Misty morning plantation walks",
      "Authentic Kodava home-cooked meals",
    ],
    faqs: [
      {
        question: "How do we get there?",
        answer: "We arrange a bus from Bangalore (Silk Board) that departs at 6am Friday. You can also self-drive and meet us at the estate.",
      },
    ],
    reviews: [
      {
        id: "r1",
        author: TRAVELERS[1],
        rating: 5,
        text: "Best use of a weekend ever. I've been to Coorg before but this way — with the estate stay and guided trails — was completely different.",
        date: "2025-07-14",
        tripDate: "Jul 2025",
        verified: true,
      },
    ],
    lat: 12.4244,
    lng: 75.7382,
    address: "Coorg, Karnataka, India",
    trending: false,
    aiPick: false,
    isWeekendEscape: true,
    isFeatured: false,
  },

  {
    id: "exp-morocco-sahara",
    title: "Morocco & the Sahara — A Desert Odyssey",
    tagline: "Medinas, camels and a billion stars",
    description:
      "Marrakech medinas, blue Chefchaouen alleys, the Sahara Desert at sunrise, Berber camps under the stars, and coastal Essaouira to close. Morocco is the kind of place that makes you question why you ever stayed home.",
    agency: AGENCIES[0],
    destination: DESTINATIONS[4],
    heroImage: U("photo-1539037116277-4db20889f2d4", 1400),
    gallery: [U("photo-1539037116277-4db20889f2d4", 900)],
    price: 95000,
    currency: "INR",
    duration: "10 Days",
    durationDays: 10,
    dates: [
      {
        id: "d1",
        startDate: "2026-10-15",
        endDate: "2026-10-24",
        seatsTotal: 12,
        seatsLeft: 7,
      },
    ],
    seatsTotal: 12,
    seatsLeft: 7,
    travelers: TRAVELERS.slice(1, 4),
    rating: 4.8,
    reviewCount: 89,
    category: "Backpacking",
    tags: ["Desert", "Camel", "Sahara", "Culture", "Morocco"],
    difficulty: "Easy",
    included: [
      "Return flights from Mumbai",
      "9 nights accommodation (riads + Sahara camp)",
      "Camel trek in the Sahara",
      "Berber camp stay",
      "All breakfasts",
      "Local guide throughout",
      "Private transport",
    ],
    excluded: ["Visa fees", "Lunch/dinner", "Personal shopping", "Travel insurance"],
    itinerary: [
      {
        day: 1,
        title: "Marrakech — Enter the Medina",
        description: "Land in Marrakech. Check into your riad, then dive into the Djemaa el-Fna square at night. Snake charmers, storytellers, food carts.",
        activities: ["Riad check-in", "Djemaa el-Fna evening", "Street food tour"],
        meals: ["Dinner"],
        accommodation: "Riad Zitoun",
        image: U("photo-1539037116277-4db20889f2d4", 600),
      },
    ],
    highlights: [
      "Sahara Desert sunrise camel ride",
      "Berber camp under a billion stars",
      "Blue city of Chefchaouen",
      "Marrakech medina and souks",
      "Coastal Essaouira at sunset",
    ],
    faqs: [
      {
        question: "Is Morocco safe to travel?",
        answer: "Yes, Morocco is a popular and safe destination for tourists. Our guides are local experts who navigate all logistics seamlessly.",
      },
    ],
    reviews: [
      {
        id: "r1",
        author: TRAVELERS[0],
        rating: 5,
        text: "The Sahara night was transcendent. Sleeping in a Berber tent, no phone signal, just stars and silence. Never felt more alive.",
        date: "2025-10-28",
        tripDate: "Oct 2025",
        verified: true,
      },
    ],
    lat: 31.6295,
    lng: -7.9811,
    address: "Marrakech, Morocco (Circular Route)",
    trending: false,
    aiPick: true,
    isWeekendEscape: false,
    isFeatured: false,
  },

  {
    id: "exp-kerala-houseboat",
    title: "Kerala Backwaters Slow Travel",
    tagline: "A houseboat, a banana leaf, and nothing to do",
    description:
      "Float through Kerala's legendary backwaters on a private houseboat. Watch village life unfold on the banks. Eat the freshest fish curry. Fall asleep to the sound of water. This one's for when your soul needs nothing but slow.",
    agency: AGENCIES[2],
    destination: {
      id: "kerala",
      name: "Kerala",
      country: "India",
      continent: "Asia",
      tagline: "God's own country",
      image: U("photo-1602216056096-3b40cc0c9944", 600),
      coverImage: U("photo-1602216056096-3b40cc0c9944", 1400),
      lat: 9.4981,
      lng: 76.3388,
      countryCode: "IN",
      trending: false,
    },
    heroImage: U("photo-1602216056096-3b40cc0c9944", 1400),
    gallery: [U("photo-1602216056096-3b40cc0c9944", 900)],
    price: 12000,
    currency: "INR",
    duration: "4 Days",
    durationDays: 4,
    dates: [
      {
        id: "d1",
        startDate: "2026-08-28",
        endDate: "2026-08-31",
        seatsTotal: 16,
        seatsLeft: 9,
      },
    ],
    seatsTotal: 16,
    seatsLeft: 9,
    travelers: TRAVELERS.slice(2, 5),
    rating: 4.6,
    reviewCount: 445,
    category: "Wellness",
    tags: ["Houseboat", "Backwaters", "Slow Travel", "Kerala", "Food"],
    difficulty: "Easy",
    included: ["3 nights on private houseboat", "All meals (Kerala cuisine)", "Village walks", "Canoe ride", "Ayurvedic session"],
    excluded: ["Travel to/from Alleppey", "Personal shopping"],
    itinerary: [
      {
        day: 1,
        title: "Board the Houseboat in Alleppey",
        description: "Arrive in Alleppey, board your traditional kettuvallam houseboat. Drift into the canals as lunch is served fresh from the onboard kitchen.",
        activities: ["Houseboat boarding", "Backwater cruise", "Sunset viewing"],
        meals: ["Lunch", "Dinner"],
        accommodation: "Private Houseboat on Vembanad Lake",
      },
    ],
    highlights: ["Private houseboat on Vembanad Lake", "Traditional Kerala meals", "Dawn canoe through narrow canals", "Village walk and local fish market"],
    faqs: [
      {
        question: "Is the houseboat private?",
        answer: "Yes, for groups of up to 6 you get a private houseboat. For solo travelers we match you with a group houseboat at a shared rate.",
      },
    ],
    reviews: [
      {
        id: "r1",
        author: TRAVELERS[5],
        rating: 5,
        text: "Genuinely the most peaceful trip I've ever taken. The sound of water, the fresh food, the total absence of phone signal. Bliss.",
        date: "2025-05-10",
        tripDate: "May 2025",
        verified: true,
      },
    ],
    lat: 9.4981,
    lng: 76.3388,
    address: "Alleppey, Kerala, India",
    trending: false,
    aiPick: false,
    isWeekendEscape: true,
    isFeatured: false,
  },

  {
    id: "exp-nz-adventure",
    title: "New Zealand — Lord of the Rings Road Trip",
    tagline: "Middle-earth is real. Let's prove it.",
    description:
      "Queenstown's adrenaline, Hobbiton's magic, and Milford Sound's alien beauty. New Zealand is the kind of country that makes you believe in a higher power. 12 days by campervan through both islands.",
    agency: AGENCIES[1],
    destination: DESTINATIONS[6],
    heroImage: U("photo-1476514525535-07fb3b4ae5f1", 1400),
    gallery: [U("photo-1476514525535-07fb3b4ae5f1", 900)],
    price: 210000,
    currency: "INR",
    duration: "12 Days",
    durationDays: 12,
    dates: [
      {
        id: "d1",
        startDate: "2027-01-05",
        endDate: "2027-01-16",
        seatsTotal: 8,
        seatsLeft: 5,
      },
    ],
    seatsTotal: 8,
    seatsLeft: 5,
    travelers: TRAVELERS.slice(0, 2),
    rating: 4.9,
    reviewCount: 67,
    category: "Road Trips",
    tags: ["Road Trip", "Adventure", "New Zealand", "Campervan", "Nature"],
    difficulty: "Moderate",
    included: ["Return flights from Mumbai", "Campervan rental (shared)", "Campervan parks & booking", "Hobbiton tour ticket", "Bungee jump session", "Milford Sound cruise"],
    excluded: ["Personal food (budget ₹1,500/day)", "Visa fees", "Travel insurance"],
    itinerary: [
      {
        day: 1,
        title: "Land in Auckland — Pick Up the Van",
        description: "Arrive in Auckland, pick up your campervan, and hit the road north toward the Coromandel Peninsula.",
        activities: ["Van pickup", "Coromandel drive", "Cathedral Cove walk"],
        meals: [],
        accommodation: "Campervan — Whitianga Camp",
      },
    ],
    highlights: [
      "Hobbiton Movie Set",
      "Bungee jump in Queenstown",
      "Milford Sound cruise",
      "Tongariro Alpine Crossing",
      "Glowworm Caves at Waitomo",
    ],
    faqs: [
      {
        question: "Do I need a driving license?",
        answer: "Yes — a valid Indian driving license works in New Zealand for up to 12 months. International Driving Permit recommended for insurance purposes.",
      },
    ],
    reviews: [
      {
        id: "r1",
        author: TRAVELERS[4],
        rating: 5,
        text: "Hobbiton made me ugly cry. The Tongariro crossing nearly killed me. Both were the best experiences of my life.",
        date: "2026-01-20",
        tripDate: "Jan 2026",
        verified: true,
      },
    ],
    lat: -45.0312,
    lng: 168.6626,
    address: "Auckland to Queenstown, New Zealand",
    trending: true,
    aiPick: false,
    isWeekendEscape: false,
    isFeatured: false,
  },

  // ── INTERNATIONAL ADDITIONS ──────────────────────────────────────────────

  {
    id: "exp-santorini",
    title: "Santorini & Greek Islands Cruise",
    tagline: "Blue domes, infinity pools, Aegean sunsets",
    description:
      "Seven days island-hopping around the Aegean. Santorini's iconic Oia sunset. Mykonos nightlife. Naxos's hidden beaches. And a sailing day on a private catamaran between it all. Greece hits different when you're not in a resort — you're in a whitewashed village eating fresh octopus and watching the sun melt into the sea.",
    agency: AGENCIES[1],
    destination: DESTINATIONS.find(d => d.id === "santorini")!,
    heroImage: U("photo-1570077188670-e3a8d69ac5ff", 1400),
    gallery: [
      U("photo-1570077188670-e3a8d69ac5ff", 900),
      U("photo-1555993539-1732b0258235", 900),
      U("photo-1613395877344-13d4a8e0d49e", 900),
      U("photo-1476514525535-07fb3b4ae5f1", 900),
    ],
    price: 145000,
    currency: "INR",
    duration: "7 Days",
    durationDays: 7,
    dates: [
      { id: "d1", startDate: "2026-06-15", endDate: "2026-06-21", seatsTotal: 12, seatsLeft: 5 },
      { id: "d2", startDate: "2026-09-01", endDate: "2026-09-07", seatsTotal: 12, seatsLeft: 8 },
    ],
    seatsTotal: 12,
    seatsLeft: 5,
    travelers: TRAVELERS.slice(1, 5),
    rating: 4.9,
    reviewCount: 143,
    category: "Road Trips",
    tags: ["Greece", "Islands", "Sailing", "Beach", "Sunset", "Mediterranean"],
    difficulty: "Easy",
    included: [
      "Return flights from Mumbai",
      "6 nights (boutique hotels + 1 night on catamaran)",
      "Private catamaran day-sail",
      "Oia sunset walking tour",
      "Ferry tickets between islands",
      "Daily breakfast + 2 welcome dinners",
      "Local Greek guide",
    ],
    excluded: ["Visa fees (~₹5,000)", "Lunches & most dinners", "Personal shopping", "Travel insurance"],
    itinerary: [
      {
        day: 1,
        title: "Arrive in Santorini — Fira at Dusk",
        description: "Land in Santorini, check into your cave hotel in Fira. Explore the clifftop village and catch your first Aegean sunset over a glass of Assyrtiko wine.",
        activities: ["Cave hotel check-in", "Fira village walk", "Cliff-side sunset dinner"],
        meals: ["Dinner"],
        accommodation: "Lava Suites, Fira",
        image: U("photo-1570077188670-e3a8d69ac5ff", 600),
      },
      {
        day: 2,
        title: "Oia — The World's Most Famous Sunset",
        description: "Morning hike from Fira to Oia along the caldera rim. Explore the blue-domed churches. In the evening, join hundreds of people watching the sun sink behind the volcano — and understand why they all came.",
        activities: ["Caldera rim hike", "Oia village wander", "Sunset from the castle"],
        meals: ["Breakfast"],
        accommodation: "Lava Suites, Fira",
        image: U("photo-1613395877344-13d4a8e0d49e", 600),
      },
      {
        day: 3,
        title: "Private Catamaran — Sail the Caldera",
        description: "Full day on a private catamaran. Swim in the hot springs near the volcanic island, snorkel at Nea Kameni, and anchor for a BBQ lunch on deck with the best view on earth.",
        activities: ["Catamaran sail", "Hot spring swim", "Snorkeling", "BBQ on deck"],
        meals: ["Breakfast", "BBQ Lunch"],
        accommodation: "Catamaran overnight",
      },
    ],
    highlights: [
      "Oia sunset from the castle ruins",
      "Private catamaran through the Santorini caldera",
      "Mykonos windmills at golden hour",
      "Fresh octopus on a Naxos harbour",
      "Swim in the volcanic hot springs",
    ],
    faqs: [
      {
        question: "When is the best time to go?",
        answer: "June and September are perfect — warm sea, fewer crowds than July–August, and long golden evenings. We avoid peak summer deliberately.",
      },
      {
        question: "Is it suitable for solo travellers?",
        answer: "Absolutely. Most of our Greek Islands groups are solo travellers. The vibe is social and laid-back from day one.",
      },
    ],
    reviews: [
      {
        id: "r1",
        author: TRAVELERS[3],
        rating: 5,
        text: "The catamaran day was the single best day of my life. Swimming off the side of the boat with the Santorini caldera in view. I cannot describe it.",
        date: "2025-09-14",
        tripDate: "Sep 2025",
        verified: true,
        images: [U("photo-1570077188670-e3a8d69ac5ff", 400)],
      },
      {
        id: "r2",
        author: TRAVELERS[5],
        rating: 5,
        text: "The Oia sunset walk with the guide gave so much context. Not just pretty — genuinely meaningful experience.",
        date: "2025-06-22",
        tripDate: "Jun 2025",
        verified: true,
      },
    ],
    lat: 36.3932,
    lng: 25.4615,
    address: "Santorini, Mykonos & Naxos, Greece",
    trending: true,
    aiPick: true,
    isWeekendEscape: false,
    isFeatured: true,
    badge: "Hot",
  },

  {
    id: "exp-patagonia",
    title: "Patagonia — Torres del Paine Trek",
    tagline: "The end of the world. The beginning of everything.",
    description:
      "The W Trek through Torres del Paine National Park is one of the planet's great walks. Granite towers that pierce the sky. Glaciers the colour of mint. Condors wheeling overhead. Pumas in the distance. Guanacos everywhere. Eight days in Chilean Patagonia will rearrange your priorities in the best possible way.",
    agency: AGENCIES[0],
    destination: DESTINATIONS.find(d => d.id === "patagonia")!,
    heroImage: U("photo-1519681393784-d120267933ba", 1400),
    gallery: [
      U("photo-1519681393784-d120267933ba", 900),
      U("photo-1476514525535-07fb3b4ae5f1", 900),
      U("photo-1464822759023-fed622ff2c3b", 900),
    ],
    price: 185000,
    currency: "INR",
    duration: "9 Days",
    durationDays: 9,
    dates: [
      { id: "d1", startDate: "2026-11-20", endDate: "2026-11-28", seatsTotal: 8, seatsLeft: 3 },
      { id: "d2", startDate: "2027-01-10", endDate: "2027-01-18", seatsTotal: 8, seatsLeft: 6 },
    ],
    seatsTotal: 8,
    seatsLeft: 3,
    travelers: TRAVELERS.slice(0, 3),
    rating: 5.0,
    reviewCount: 61,
    category: "Trekking",
    tags: ["Patagonia", "Trek", "Chile", "Glacier", "Wilderness", "Torres del Paine"],
    difficulty: "Challenging",
    included: [
      "Return flights from Delhi via Santiago",
      "8 nights (refugios + glamping domes)",
      "Full W-Trek guided itinerary",
      "Grey Glacier boat crossing",
      "All meals on trail",
      "Park entry fees",
      "Trekking poles & crampons",
    ],
    excluded: ["Personal trekking gear", "Travel insurance", "Visa fees (~₹0, visa-free)", "Personal expenses"],
    itinerary: [
      {
        day: 1,
        title: "Fly into Punta Arenas — Welcome to the End of the World",
        description: "Land in Punta Arenas, southernmost city on earth. Evening briefing and gear check. Dinner together looking out over the Strait of Magellan.",
        activities: ["Airport pickup", "Gear check & briefing", "City walk", "Welcome dinner"],
        meals: ["Dinner"],
        accommodation: "Punta Arenas Guesthouse",
      },
      {
        day: 2,
        title: "Torres del Paine — Enter the Park",
        description: "Morning transfer into the park. First views of the Paine Massif. Afternoon hike to Mirador Las Torres base camp.",
        activities: ["Park entry", "Mirando Las Torres hike", "Camp setup"],
        meals: ["Breakfast", "Packed Lunch", "Dinner"],
        accommodation: "Refugio Las Torres",
        image: U("photo-1519681393784-d120267933ba", 600),
      },
    ],
    highlights: [
      "Base of the Torres at sunrise (4am start — worth every second)",
      "Grey Glacier by boat — walk on 8,000-year-old ice",
      "Condor sighting on the French Valley lookout",
      "Mirador del Francés panorama",
      "Luxury glamping under Patagonian stars",
    ],
    faqs: [
      {
        question: "How fit do I need to be?",
        answer: "This is a genuine challenge. Daily hikes of 15–22km on uneven terrain. You should be able to hike 20km comfortably with a daypack. We train you with a 4-week prep plan.",
      },
      {
        question: "What's the weather like?",
        answer: "Unpredictable — four seasons in one day is not a cliché in Patagonia. Our November and January dates are peak season with the best chances of clear skies.",
      },
    ],
    reviews: [
      {
        id: "r1",
        author: TRAVELERS[0],
        rating: 5,
        text: "The Torres at 5am with the lake going pink below them. I have no words. This is the most beautiful thing I have ever seen and I've been on 30 trips.",
        date: "2025-11-30",
        tripDate: "Nov 2025",
        verified: true,
        images: [U("photo-1519681393784-d120267933ba", 400)],
      },
    ],
    lat: -51.6230,
    lng: -72.6789,
    address: "Torres del Paine National Park, Patagonia, Chile",
    trending: true,
    aiPick: true,
    isWeekendEscape: false,
    isFeatured: true,
    badge: "Top Rated",
  },

  {
    id: "exp-cappadocia",
    title: "Cappadocia — Hot Air Balloons at Dawn",
    tagline: "Float over fairy chimneys as the sun rises",
    description:
      "There is nothing on earth quite like drifting over Cappadocia at sunrise in a hot air balloon. Below you: a lunar valley of ancient cave churches, volcanic spires, and apricot orchards. Above you: 50 other balloons slowly filling the pink sky. Then comes the underground cities, the whirling dervish ceremony, and the cave hotel with a view of a thousand years of history.",
    agency: AGENCIES[1],
    destination: DESTINATIONS.find(d => d.id === "cappadocia")!,
    heroImage: U("photo-1509316785289-025f5b846b35", 1400),
    gallery: [
      U("photo-1509316785289-025f5b846b35", 900),
      U("photo-1527631746610-bca00a040d60", 900),
      U("photo-1539037116277-4db20889f2d4", 900),
    ],
    price: 88000,
    currency: "INR",
    duration: "6 Days",
    durationDays: 6,
    dates: [
      { id: "d1", startDate: "2026-04-10", endDate: "2026-04-15", seatsTotal: 10, seatsLeft: 4 },
      { id: "d2", startDate: "2026-10-05", endDate: "2026-10-10", seatsTotal: 10, seatsLeft: 7 },
    ],
    seatsTotal: 10,
    seatsLeft: 4,
    travelers: TRAVELERS.slice(2, 6),
    rating: 4.9,
    reviewCount: 178,
    category: "Backpacking",
    tags: ["Turkey", "Cappadocia", "Hot Air Balloon", "Cave Hotel", "History"],
    difficulty: "Easy",
    included: [
      "Return flights from Mumbai",
      "5 nights in cave hotels",
      "Sunrise hot air balloon ride (1.5 hrs)",
      "Göreme Open Air Museum",
      "Underground cities of Derinkuyu",
      "Whirling dervish ceremony",
      "Turkish cooking class",
      "Daily breakfast + 3 dinners",
    ],
    excluded: ["Visa on arrival (~₹2,800)", "Lunches", "Personal shopping", "Travel insurance"],
    itinerary: [
      {
        day: 1,
        title: "Land in Kayseri — Drive into the Valley",
        description: "Fly into Kayseri and transfer to your cave hotel in Göreme. Evening walk through the fairy chimney valleys at sunset — your first glimpse of Cappadocia's alien beauty.",
        activities: ["Cave hotel check-in", "Göreme valley walk", "Sunset from the ridge"],
        meals: ["Dinner"],
        accommodation: "Sultan Cave Suites, Göreme",
        image: U("photo-1509316785289-025f5b846b35", 600),
      },
      {
        day: 2,
        title: "4:30am Wake-Up — Balloon at Sunrise",
        description: "The earliest alarm of your life is worth it. Rise before dawn, meet your balloon pilot, and float silently over the valleys as the sun breaks over the horizon. Land with champagne.",
        activities: ["Hot air balloon ride", "Champagne landing", "Göreme Open Air Museum", "Rest afternoon"],
        meals: ["Breakfast", "Dinner"],
        accommodation: "Sultan Cave Suites, Göreme",
        image: U("photo-1527631746610-bca00a040d60", 600),
      },
    ],
    highlights: [
      "Sunrise hot air balloon over the Love Valley",
      "Cave hotel room carved from volcanic rock",
      "Derinkuyu underground city (18 levels deep)",
      "Whirling dervish Sema ceremony",
      "Turkish ceramics painting workshop",
    ],
    faqs: [
      {
        question: "Is the balloon ride safe?",
        answer: "Cappadocia is one of the world's premier balloon destinations. We use only licensed operators with impeccable safety records. Flights are weather-dependent and may be rescheduled.",
      },
    ],
    reviews: [
      {
        id: "r1",
        author: TRAVELERS[1],
        rating: 5,
        text: "I've been on lots of trips but nothing prepared me for floating over those valleys in total silence. The world looked like a painting. Cried happy tears.",
        date: "2025-10-12",
        tripDate: "Oct 2025",
        verified: true,
        images: [U("photo-1509316785289-025f5b846b35", 400)],
      },
      {
        id: "r2",
        author: TRAVELERS[4],
        rating: 5,
        text: "Cave hotel was mind-blowing. Woke up to views of the valley through an arched stone window. Turkey is criminally underrated.",
        date: "2025-04-18",
        tripDate: "Apr 2025",
        verified: true,
      },
    ],
    lat: 38.6431,
    lng: 34.8283,
    address: "Göreme, Cappadocia, Turkey",
    trending: true,
    aiPick: true,
    isWeekendEscape: false,
    isFeatured: true,
    badge: "Hot",
  },

  {
    id: "exp-maldives",
    title: "Maldives — Overwater Bungalow Escape",
    tagline: "Your floor is the ocean. Your alarm is the waves.",
    description:
      "Five days on a private atoll in the Maldives — staying in an overwater bungalow where the Indian Ocean laps beneath your glass floor. Snorkel with manta rays, watch bioluminescent plankton glow at midnight, eat fresh tuna on the beach, and spend mornings in absolute stillness. This is the trip you save for when you need to remember what rest actually feels like.",
    agency: AGENCIES[2],
    destination: DESTINATIONS.find(d => d.id === "maldives")!,
    heroImage: U("photo-1514282401047-d79a71a590e8", 1400),
    gallery: [
      U("photo-1514282401047-d79a71a590e8", 900),
      U("photo-1507525428034-b723cf961d3e", 900),
      U("photo-1502680390469-be75c86b636f", 900),
    ],
    price: 195000,
    currency: "INR",
    duration: "5 Days",
    durationDays: 5,
    dates: [
      { id: "d1", startDate: "2026-07-10", endDate: "2026-07-14", seatsTotal: 6, seatsLeft: 2 },
      { id: "d2", startDate: "2026-12-20", endDate: "2026-12-24", seatsTotal: 6, seatsLeft: 4 },
    ],
    seatsTotal: 6,
    seatsLeft: 2,
    travelers: TRAVELERS.slice(3, 6),
    rating: 4.9,
    reviewCount: 92,
    category: "Wellness",
    tags: ["Maldives", "Overwater", "Snorkeling", "Luxury", "Beach", "Island"],
    difficulty: "Easy",
    included: [
      "Return seaplane from Malé",
      "4 nights overwater bungalow",
      "All meals (breakfast, lunch, dinner)",
      "Manta ray snorkel tour",
      "Bioluminescent beach night walk",
      "Sunset dolphin cruise",
      "Underwater restaurant dinner",
      "Spa treatment (1 session)",
    ],
    excluded: ["Flights to Malé", "Alcohol", "Diving certification (can be arranged extra)", "Personal expenses"],
    itinerary: [
      {
        day: 1,
        title: "Seaplane into the Atoll",
        description: "Land in Malé and board your seaplane. 30 minutes of flying low over atolls shaped like perfect rings, then splash-land beside your resort. Walk your private jetty to your overwater bungalow.",
        activities: ["Seaplane transfer", "Overwater bungalow check-in", "Welcome snorkel", "Sunset cocktails"],
        meals: ["Dinner"],
        accommodation: "Overwater Bungalow, Private Atoll",
        image: U("photo-1514282401047-d79a71a590e8", 600),
      },
      {
        day: 2,
        title: "Manta Ray Snorkel — Their Ocean, Your Visit",
        description: "Early morning snorkel session with resident manta rays in the channel. Afternoon free on your bungalow deck. Evening: glass-bottom kayak at sunset.",
        activities: ["Manta ray snorkel", "Deck lounging", "Glass-bottom kayak"],
        meals: ["Breakfast", "Lunch", "Dinner"],
        accommodation: "Overwater Bungalow, Private Atoll",
      },
    ],
    highlights: [
      "Overwater bungalow with glass floor panel",
      "Snorkeling with manta rays in the wild",
      "Bioluminescent beach at midnight",
      "Underwater restaurant dinner",
      "Seaplane arrival over the Indian Ocean",
    ],
    faqs: [
      {
        question: "Is this for couples only?",
        answer: "Not at all. About 40% of our Maldives guests travel solo or with friends. The experience is universal — you don't need to be on a honeymoon to deserve this.",
      },
      {
        question: "How do we get to Malé?",
        answer: "Direct flights from Mumbai, Delhi and Bangalore are available with IndiGo and Air India at good prices. We send recommended flight options after booking.",
      },
    ],
    reviews: [
      {
        id: "r1",
        author: TRAVELERS[5],
        rating: 5,
        text: "Woke up at 3am, stepped off my bungalow into the water, and watched the entire ocean floor glow blue. I don't have the vocabulary for what that felt like.",
        date: "2025-07-20",
        tripDate: "Jul 2025",
        verified: true,
        images: [U("photo-1514282401047-d79a71a590e8", 400)],
      },
    ],
    lat: 3.2028,
    lng: 73.2207,
    address: "North Malé Atoll, Maldives",
    trending: true,
    aiPick: false,
    isWeekendEscape: false,
    isFeatured: true,
    badge: "2 left",
  },

  {
    id: "exp-norway-fjords",
    title: "Norwegian Fjords — The Scenic Rail & Hike",
    tagline: "Pulpit Rock, Bergen fish market, fjord silence",
    description:
      "Norway's fjords are the kind of scenery that makes your phone inadequate. The Bergen Railway through snowfields. The Flåm Railway dropping into the valley. A ferry through Nærøyfjord — UNESCO-listed and inexplicably narrow. And then Preikestolen: climbing 604m of cliff face to stand on a granite ledge above Lysefjord with zero barrier between you and eternity.",
    agency: AGENCIES[0],
    destination: DESTINATIONS.find(d => d.id === "norway")!,
    heroImage: U("photo-1531722569936-825d4eaf1af1", 1400),
    gallery: [
      U("photo-1531722569936-825d4eaf1af1", 900),
      U("photo-1504893524553-b855bce32c67", 900),
      U("photo-1476514525535-07fb3b4ae5f1", 900),
    ],
    price: 165000,
    currency: "INR",
    duration: "8 Days",
    durationDays: 8,
    dates: [
      { id: "d1", startDate: "2026-06-20", endDate: "2026-06-27", seatsTotal: 10, seatsLeft: 6 },
      { id: "d2", startDate: "2026-07-15", endDate: "2026-07-22", seatsTotal: 10, seatsLeft: 8 },
    ],
    seatsTotal: 10,
    seatsLeft: 6,
    travelers: TRAVELERS.slice(0, 4),
    rating: 4.8,
    reviewCount: 74,
    category: "Trekking",
    tags: ["Norway", "Fjords", "Hike", "Preikestolen", "Scenic Rail", "Midnight Sun"],
    difficulty: "Moderate",
    included: [
      "Return flights from Delhi",
      "7 nights (guesthouses + fjord-view hotel)",
      "Bergen Railway & Flåmsbana rail tickets",
      "Nærøyfjord ferry cruise",
      "Preikestolen guided hike",
      "Bergen Fish Market tour",
      "All breakfasts + 3 dinners",
    ],
    excluded: ["Visa fees (~₹8,000)", "Lunches & some dinners", "Personal expenses", "Travel insurance"],
    itinerary: [
      {
        day: 1,
        title: "Arrive in Oslo — Midnight Sun Walk",
        description: "Land in Oslo and explore the Aker Brygge waterfront. In June and July the sun barely sets — take a midnight stroll in broad daylight and try your best to process that.",
        activities: ["Oslo waterfront walk", "Vigeland Sculpture Park", "Midnight sun experience"],
        meals: ["Dinner"],
        accommodation: "Oslo City Hostel",
        image: U("photo-1531722569936-825d4eaf1af1", 600),
      },
      {
        day: 4,
        title: "Preikestolen — Pulpit Rock Hike",
        description: "The hike that Instagram never fully captures. 3.8km each way through bog, granite, and switchbacks. At the top: a perfectly flat 25x25m ledge above a 604m drop into Lysefjord. One of Norway's defining moments.",
        activities: ["Preikestolen hike (7–8 hrs return)", "Lysefjord viewpoint", "Summit lunch"],
        meals: ["Breakfast", "Packed Lunch"],
        accommodation: "Stavanger Guesthouse",
        image: U("photo-1476514525535-07fb3b4ae5f1", 600),
      },
    ],
    highlights: [
      "Stand on Preikestolen — 604m above Lysefjord",
      "Flåmsbana — one of the world's most scenic rail journeys",
      "Midnight sun in Oslo and Bergen",
      "Nærøyfjord UNESCO ferry cruise",
      "Bergen fish market and colourful Bryggen wharf",
    ],
    faqs: [
      {
        question: "Is the Preikestolen hike dangerous?",
        answer: "The trail is challenging but not technical — no ropes or climbing required. There are no barriers at the top, which is both terrifying and perfect. Take care, go slow near the edge.",
      },
    ],
    reviews: [
      {
        id: "r1",
        author: TRAVELERS[2],
        rating: 5,
        text: "Standing on Pulpit Rock in the midnight sun with the fjord 600m below. No words. This is why people travel.",
        date: "2025-06-28",
        tripDate: "Jun 2025",
        verified: true,
      },
    ],
    lat: 60.4720,
    lng: 8.4689,
    address: "Oslo, Bergen & Lysefjord, Norway",
    trending: false,
    aiPick: false,
    isWeekendEscape: false,
    isFeatured: false,
  },

  {
    id: "exp-vietnam",
    title: "Vietnam — Hanoi to Ha Long Bay",
    tagline: "Street pho at dawn, limestone karsts at dusk",
    description:
      "Vietnam in 8 days: the chaotic, beautiful streets of Hanoi's Old Quarter, a junk boat cruise through Ha Long Bay's 1,500 limestone islands, Hội An's ancient lantern-lit streets, and the rice terraces of Sapa. Southeast Asia at its most photogenic, layered with history, flavour, and the kind of warmth you remember for years.",
    agency: AGENCIES[1],
    destination: DESTINATIONS.find(d => d.id === "vietnam")!,
    heroImage: U("photo-1528181304800-259b08848526", 1400),
    gallery: [
      U("photo-1528181304800-259b08848526", 900),
      U("photo-1528360983277-13d401cdc186", 900),
      U("photo-1540959733332-eab4deabeeaf", 900),
    ],
    price: 75000,
    currency: "INR",
    duration: "8 Days",
    durationDays: 8,
    dates: [
      { id: "d1", startDate: "2026-03-10", endDate: "2026-03-17", seatsTotal: 14, seatsLeft: 9 },
      { id: "d2", startDate: "2026-10-20", endDate: "2026-10-27", seatsTotal: 14, seatsLeft: 11 },
    ],
    seatsTotal: 14,
    seatsLeft: 9,
    travelers: TRAVELERS.slice(1, 5),
    rating: 4.8,
    reviewCount: 156,
    category: "Backpacking",
    tags: ["Vietnam", "Ha Long Bay", "Hanoi", "Hội An", "Street Food", "Junk Boat"],
    difficulty: "Easy",
    included: [
      "Return flights from Delhi",
      "7 nights accommodation (hostel + junk boat + heritage hotel)",
      "2-night Ha Long Bay junk boat cruise",
      "Hanoi Old Quarter walking tour",
      "Hội An lantern-making class",
      "Cooking class: pho, bánh mì, fresh rolls",
      "All breakfasts + 4 dinners",
    ],
    excluded: ["Visa on arrival (~₹1,500)", "Lunches", "Personal shopping", "Travel insurance"],
    itinerary: [
      {
        day: 1,
        title: "Land in Hanoi — Old Quarter by Night",
        description: "Arrive in Hanoi. Drop your bags and head into the Old Quarter — 36 streets named after what they once sold. Egg coffee at Giang Cafe. Bun cha for dinner. Walk past Hoan Kiem Lake at midnight.",
        activities: ["Old Quarter walk", "Hoan Kiem Lake at night", "Egg coffee stop", "Bun cha dinner"],
        meals: ["Dinner"],
        accommodation: "Hanoi Old Quarter Boutique Hotel",
        image: U("photo-1528181304800-259b08848526", 600),
      },
      {
        day: 3,
        title: "Board the Junk Boat — Ha Long Bay",
        description: "4-hour drive east to Ha Long Bay. Board your overnight junk boat and sail into 1,500 limestone karsts rising from emerald water. Kayak into hidden lagoons, swim off the boat, eat fresh seafood on deck.",
        activities: ["Junk boat boarding", "Kayaking through karst caves", "Sunset on deck", "Fresh seafood dinner"],
        meals: ["Breakfast", "Lunch", "Dinner"],
        accommodation: "Junk Boat on Ha Long Bay",
        image: U("photo-1528181304800-259b08848526", 600),
      },
    ],
    highlights: [
      "Overnight junk boat cruise through Ha Long Bay",
      "Kayaking into the Luon Cave lagoon",
      "Hanoi Old Quarter on a motorbike",
      "Hội An lantern festival (if timing aligns)",
      "Vietnamese cooking class — pho from scratch",
    ],
    faqs: [
      {
        question: "Is Ha Long Bay crowded?",
        answer: "We pick boats and launch areas away from the main tourist clusters. The bay is vast — with the right operator you can have a lagoon entirely to yourself.",
      },
    ],
    reviews: [
      {
        id: "r1",
        author: TRAVELERS[4],
        rating: 5,
        text: "Kayaking through a cave and emerging into a secret lagoon surrounded by karst walls with no one else around. That's a memory I'll keep forever.",
        date: "2025-10-28",
        tripDate: "Oct 2025",
        verified: true,
        images: [U("photo-1528181304800-259b08848526", 400)],
      },
      {
        id: "r2",
        author: TRAVELERS[3],
        rating: 4,
        text: "Vietnam exceeded every expectation. The food alone is worth the trip. Hanoi egg coffee is life-changing.",
        date: "2025-03-18",
        tripDate: "Mar 2025",
        verified: true,
      },
    ],
    lat: 20.9101,
    lng: 107.1839,
    address: "Hanoi, Ha Long Bay & Hội An, Vietnam",
    trending: true,
    aiPick: true,
    isWeekendEscape: false,
    isFeatured: true,
    badge: "Sold Fast",
  },
];

// ─── Current User ─────────────────────────────────────────────────────────────

export const CURRENT_USER: User = {
  id: "user-current",
  name: "Arjun Mehta",
  avatar: U("photo-1507003211169-0a1dd7228f2d", 300),
  coverImage: U("photo-1476514525535-07fb3b4ae5f1", 1200),
  hometown: "Bangalore, India",
  bio: "Restless soul. Mountains > meetings. Collecting passport stamps and bad tan lines since 2018.",
  countriesVisited: ["IN", "JP", "ID", "TH", "NP", "LK", "MV", "SG"],
  tripsCompleted: 14,
  totalDaysOnRoad: 187,
  wishlist: ["exp-iceland-aurora", "exp-nz-adventure", "exp-morocco-sahara"],
  badges: [
    {
      id: "b1",
      name: "First Step",
      description: "Completed your first trip on ROVER",
      iconName: "MapPin",
      color: "#F59E0B",
      earned: true,
      earnedDate: "2024-03-15",
    },
    {
      id: "b2",
      name: "High Altitude",
      description: "Trekked above 4,000m",
      iconName: "Mountains",
      color: "#6366F1",
      earned: true,
      earnedDate: "2024-09-22",
    },
    {
      id: "b3",
      name: "Ocean Soul",
      description: "Completed a surf experience",
      iconName: "Waves",
      color: "#0EA5E9",
      earned: false,
    },
    {
      id: "b4",
      name: "Campfire",
      description: "Camped under the stars on a ROVER trip",
      iconName: "Campfire",
      color: "#EF4444",
      earned: true,
      earnedDate: "2024-09-24",
    },
    {
      id: "b5",
      name: "Solo Brave",
      description: "Took your first solo trip",
      iconName: "User",
      color: "#8B5CF6",
      earned: false,
    },
    {
      id: "b6",
      name: "Continent 2",
      description: "Traveled to a second continent",
      iconName: "Globe",
      color: "#10B981",
      earned: true,
      earnedDate: "2025-01-10",
    },
  ],
  travelStreak: 3,
  memberSince: "2024-01-15",
  instagram: "@arjun.ontheroad",
  followers: 1247,
  following: 389,
};

// ─── Active Trips ─────────────────────────────────────────────────────────────

export const MY_TRIPS: Trip[] = [
  {
    id: "trip-001",
    experience: EXPERIENCES[0],
    status: "upcoming",
    bookingDate: "2026-06-12",
    departureDate: "2026-09-05",
    returnDate: "2026-09-14",
    travelers: 1,
    totalPaid: 45000,
    bookingRef: "RVR-2026-SPITI-001",
    documents: [
      {
        id: "doc-1",
        name: "Trip Confirmation",
        type: "voucher",
        url: "#",
        uploadedAt: "2026-06-12",
      },
      {
        id: "doc-2",
        name: "Packing Checklist",
        type: "voucher",
        url: "#",
        uploadedAt: "2026-06-12",
      },
    ],
    paymentStatus: "paid",
  },
  {
    id: "trip-003",
    experience: EXPERIENCES[4],
    status: "upcoming",
    bookingDate: "2026-07-20",
    departureDate: "2026-10-12",
    returnDate: "2026-10-17",
    travelers: 2,
    totalPaid: 38000,
    bookingRef: "RVR-2026-COORG-003",
    documents: [
      {
        id: "doc-5",
        name: "Booking Voucher",
        type: "voucher",
        url: "#",
        uploadedAt: "2026-07-20",
      },
    ],
    paymentStatus: "paid",
  },
  {
    id: "trip-002",
    experience: EXPERIENCES[2],
    status: "completed",
    bookingDate: "2025-07-01",
    departureDate: "2025-08-10",
    returnDate: "2025-08-16",
    travelers: 1,
    totalPaid: 55000,
    bookingRef: "RVR-2025-BALI-002",
    documents: [
      {
        id: "doc-3",
        name: "Flight e-Ticket",
        type: "ticket",
        url: "#",
        uploadedAt: "2025-07-15",
      },
      {
        id: "doc-4",
        name: "Hotel Voucher",
        type: "voucher",
        url: "#",
        uploadedAt: "2025-07-15",
      },
    ],
    paymentStatus: "paid",
  },
  {
    id: "trip-004",
    experience: EXPERIENCES[1],
    status: "completed",
    bookingDate: "2025-02-01",
    departureDate: "2025-03-20",
    returnDate: "2025-03-27",
    travelers: 1,
    totalPaid: 72000,
    bookingRef: "RVR-2025-JAPAN-004",
    documents: [
      {
        id: "doc-6",
        name: "Japan Visa Copy",
        type: "voucher",
        url: "#",
        uploadedAt: "2025-03-01",
      },
    ],
    paymentStatus: "paid",
  },
  {
    id: "trip-005",
    experience: EXPERIENCES[5],
    status: "cancelled",
    bookingDate: "2024-11-10",
    departureDate: "2024-12-24",
    returnDate: "2024-12-31",
    travelers: 1,
    totalPaid: 0,
    bookingRef: "RVR-2024-MALD-005",
    documents: [],
    paymentStatus: "pending",
  },
];

// ─── Community Posts ──────────────────────────────────────────────────────────

export const COMMUNITY_POSTS: CommunityPost[] = [
  {
    id: "post-1",
    author: TRAVELERS[0],
    destination: DESTINATIONS[0],
    content:
      "The silence at Chandratal Lake at 3am is something I didn't know I needed. No phone signal. Just the Milky Way reflected perfectly in the water. Changed me.",
    images: [U("photo-1476514525535-07fb3b4ae5f1", 600)],
    likes: 847,
    comments: 64,
    timestamp: "2026-07-28T18:23:00Z",
    tags: ["spiti", "chandratal", "himalayas"],
    isLiked: false,
  },
  {
    id: "post-2",
    author: TRAVELERS[1],
    destination: DESTINATIONS[1],
    content:
      "Tokyo at 2am hits different. Empty Shibuya crossing. Just me, the crossing, and the realization that I'm actually here. 12-year-old me would be losing their mind.",
    images: [U("photo-1540959733332-eab4deabeeaf", 600), U("photo-1493976040374-85c8e12f0c0e", 600)],
    likes: 1203,
    comments: 88,
    timestamp: "2026-07-30T02:45:00Z",
    tags: ["tokyo", "japan", "shibuya", "nightlife"],
    isLiked: true,
  },
  {
    id: "post-3",
    author: TRAVELERS[2],
    destination: DESTINATIONS[3],
    content:
      "Day 5 in Iceland. I've stopped trying to take photos. Some things you just have to live. The Northern Lights tonight were 45 minutes of unexplainable green magic.",
    images: [U("photo-1504893524553-b855bce32c67", 600)],
    likes: 2156,
    comments: 143,
    timestamp: "2026-07-25T22:10:00Z",
    tags: ["iceland", "northernlights", "aurora"],
    isLiked: false,
  },
  {
    id: "post-4",
    author: TRAVELERS[4],
    content:
      "PSA: you can do Coorg on ₹8,500 and feel like you spent ₹80,000. Found this little coffee estate via ROVER and it's been the best decision of 2026.",
    images: [],
    likes: 512,
    comments: 37,
    timestamp: "2026-07-31T09:30:00Z",
    tags: ["coorg", "weekendgetaway", "bangalore"],
    isLiked: false,
  },
];
